name: Validate pull request

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]
    paths:
      - 'force-app/**'

jobs:
  validate-deployment:
    runs-on: ubuntu-latest
    container:
      image: salesforce/cli:latest-slim
    steps:      
      - name: Install SGD
        run: echo y | sf plugins install "sfdx-git-delta@${{ vars.SGD_VERSION }}"

      - name: 'Checkout source code'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: 'Ensure full Git history is available'
        run: |
          git fetch --unshallow
          git fetch origin +refs/heads/*:refs/remotes/origin/*
          git branch --force main origin/main
          git branch --show-current  # Debugging: Show current branch

      - name: 'Create delta packages for new, modified, or deleted metadata'
        run: | 
            mkdir changed-sources
            sf sgd source delta --to "HEAD" --from "origin/${{ github.base_ref }}" --output-dir "." --generate-delta --source-dir force-app/
      
      - name: 'Authenticate using SFDX_AUTH_URL'
        run: | 
          echo ${{ secrets.SFDX_AUTH_URL }} | sf org login sfdx-url -s -u

      - name: 'Validate'
        run: |
          sf project deploy validate -x package/package.xml -l RunLocalTests -w 30          
